### PR TITLE
fix(react-router): memoize Match, MatchInner as well as route components to prevent unnecessary re-renders

### LINKED ISSUE #1462: I'm reaching out to report a performance issue.
I'm reaching out to report a performance issue.

The problem involves performance in two scenarios:

1. When updating the search parameters using `useNavigation`, the entire page, including all layout components and child components, is re-rendered.
2. When there is a layout component with multiple child pages, navigating between these child pages triggers a re-render of the entire page, including all layout components.

In the classic `react-router` package, this problem does not exist, there it works as expected, parts are rerendered as expected.

Example Link: https://stackblitz.com/edit/vitejs-vite-ifxs98

_Originally posted by @AndrejNemec in https://github.com/TanStack/router/discussions/1460_

### PR DESCRIPTION
**Pull request by schiller-manuel**
fixes #1462

### CODE REVIEW

File: packages/react-router/src/Match.tsx [hunk 1]
```diff
@@ -127,6 +136,10 @@ function MatchInner({ matchId }: { matchId: string }): any {
     },
   })
 
+  const Comp = route.options.component ?? router.options.defaultComponent
+
+  const out = React.useMemo(() => (Comp ? <Comp /> : <Outlet />), [Comp])
```
Comment (SeanCassiere) [inline packages/react-router/src/Match.tsx:141]: It may be worth checking out the benefit of using the `matchId` as the key on the `<Comp/>`.

Ultimately may not be what we are looking for if stuff like `useSearch` doesn't trigger a re-render, but might be worth checking out.

File: packages/react-router/src/Match.tsx [hunk 2]
```diff
@@ -127,6 +136,10 @@ function MatchInner({ matchId }: { matchId: string }): any {
     },
   })
 
+  const Comp = route.options.component ?? router.options.defaultComponent
```
Comment (SeanCassiere) [inline packages/react-router/src/Match.tsx:139]: Could this also be memoed? Or maybe pulled into `useMemo` below?

Since these values don't change very often, there is no need to recompute this.

File: packages/react-router/src/Match.tsx [hunk 3]
```diff
@@ -16,7 +16,11 @@ import { renderRouteNotFound } from './renderRouteNotFound'
 import { rootRouteId } from './root'
 import type { AnyRoute } from './route'
 
-export function Match({ matchId }: { matchId: string }) {
+export const Match = React.memo(function Match({
```
Comment (SeanCassiere) [inline packages/react-router/src/Match.tsx:19]: Could we name the inner `Match` as `MatchImpl`?

Same for `MatchInner` and `Outlet`.

File: packages/react-router/src/Match.tsx (hunk 2 above)
Comment (schiller-manuel) [reply packages/react-router/src/Match.tsx]: done

File: packages/react-router/src/Match.tsx (hunk 3 above)
Comment (schiller-manuel) [reply packages/react-router/src/Match.tsx]: done

File: packages/react-router/src/Match.tsx (hunk 1 above)
Comment (schiller-manuel) [reply packages/react-router/src/Match.tsx]: like this?

```tsx
<Comp key={matchId}/> 
```

which effect would you expect from that?

Comment (SeanCassiere) [reply packages/react-router/src/Match.tsx]: Yup. 

It's since keyed components don't re-render unless the key changes, it may help.

And we shouldn't have to worry about the render being stale, since the `matchId` changes if actual match info has changed.

Comment (schiller-manuel) [reply packages/react-router/src/Match.tsx]: tried it with kitchen sink example, using the `matchId` as key causes the `InvoiceComponent` to be rendered only once instead of twice without it.
great find!

Comment (SeanCassiere) [reply packages/react-router/src/Match.tsx]: 🚀

Yeah it's a simple hack I tend to use to either trigger a child component's re-render or to prevent unneeded renders.

**Review by SeanCassiere — APPROVED** [review]
