### PR TITLE
fix(start): returning `null` from server functions

### LINKED ISSUE #2776: Start: createServerFn cannot return `null`
### Which project does this relate to?

Router

### Describe the bug

All details are found in this discussion thread on Discord - https://discord.com/channels/719702312431386674/1306957125246914590

The crust of the matter is that you aren't able to return `null` from a `createServerFn` call.

```ts
const fn = createServerFn().handler(async () => {
    return null
})

await fn(); // undefined
```

### Your Example Website or App

https://discord.com/channels/719702312431386674/1306957125246914590

### Steps to Reproduce the Bug or Issue

Create a server function returning `null` and see that at runtime it does not return the value, instead, it returns `undefined`.

### Expected behavior

The returned `null` value from the server function should correctly get piped down to the caller.

### Screenshots or Videos

_No response_

### Platform

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alakhpc**
Fixes #2776, pass through null returns from serverfns

### CODE REVIEW

**Comment by schiller-manuel** [comment]
can you please cherry-pick this on top? https://github.com/TanStack/router/pull/2778

**Comment by alakhpc** [comment]
I had to update the test from

```ts
getServerResult ?? '-'
```
to 
```ts
getServerResult !== undefined ? getServerResult : '-'
```

should be good now

File: e2e/start/basic/app/routes/-server-fns/allow-fn-return-null.tsx [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+            getServerResult !== undefined ? getServerResult : '-',
+          )}
+        </span>
+      </p>
+      <p>
+        {`POST: $allow_return_null_postFn returns`}
+        <br />
+        <span data-testid="allow_return_null_postFn-response">
+          {JSON.stringify(
+            postServerResult !== undefined ? postServerResult : '-',
```
Comment (SeanCassiere) [inline e2e/start/basic/app/routes/-server-fns/allow-fn-return-null.tsx:50]: Maybe the `useState` values should be initialized with something else that's not falsy. Like `-` or something else. I don't like the fact that we are doing conditional checking here in the test.
This test component really should just be stringifying whatever the stored result is.

Comment (alakhpc) [reply e2e/start/basic/app/routes/-server-fns/allow-fn-return-null.tsx]: updated

File: packages/start/src/client/createServerFn.ts [hunk 2]
```diff
@@ -365,7 +365,10 @@ const applyMiddleware = (
         context,
         sendContext,
         headers,
-        result: userResult?.result ?? (mCtx as any).result,
+        result:
```
Comment (SeanCassiere) [inline packages/start/src/client/createServerFn.ts:368]: I'm not going to lie. I still don't understand why this change fixes the issue. Since at runtime, both conditions should resolve the same thing. 
¯\_(ツ)_/¯

**Review by SeanCassiere — APPROVED** [review]

File: packages/start/src/client/createServerFn.ts (hunk 2 above)
Comment (TkDodo) [reply packages/start/src/client/createServerFn.ts:368]: previously, when userResult.result was `null`, we retuned mCtx.result because ?? returns the fallback for both null and undefined. 

Now, since we check for undefined explicitly, null will be "passed through".

Comment (SeanCassiere) [reply packages/start/src/client/createServerFn.ts:368]: Omg... I totally thought that `??` only ever passed through when it was `undefined` 🤯.

**Comment by SeanCassiere** [comment]
@alakhpc thank you for contributing this fix 🎉
