### PR TITLE
fix(react-router): when navigating without `to` the layout segments are not being stripped out

### LINKED ISSUE #1560: `navigate` functions without `to` but with `search` causes a route error inside a layout route.
### Describe the bug

After version `1.31.7` the error started occurring. Related to #1548. @SeanCassiere

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-1udi7f?file=src%2Froutes%2F_test%2Ftabs-example.%24someId.tsx

### Steps to Reproduce the Bug or Issue

Go to "Tabs example" route, change the tab and the error is caused. If you put the URL manually, let's say `...?tab=tab2` it renders well, but as soon as you change the tab the app crash

### Expected behavior

Both tabs work well without crashing the app.

### Screenshots or Videos

_No response_

### Platform

- OS: [macOS]
- Browser: [Arc]
- Version: [1.31.7]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SeanCassiere**
#1548 didn't account for layout routes as pointed out in #1560.

FIxes #1560

### CODE REVIEW

File: packages/react-router/src/utils.ts
Comment (SeanCassiere) [inline packages/react-router/src/utils.ts:1]: Copied this straight out of what we using in the generator.

File: packages/react-router/src/utils.ts [hunk 1]
```diff
@@ -339,3 +339,17 @@ export function createControlledPromise<T>(onResolve?: () => void) {
...
+
+/**
+ * Removes all segments from a given path that start with an underscore ('_').
+ *
+ * @param {string} routePath - The path from which to remove segments. Defaults to '/'.
+ * @returns {string} The path with all underscore-prefixed segments removed.
+ * @example
+ * removeLayoutSegments('/workspace/_auth/foo') // '/workspace/foo'
+ */
+export function removeLayoutSegments(routePath: string): string {
```
Comment (schiller-manuel) [inline packages/react-router/src/utils.ts:351]: can you add a test for this please?

**Comment by schiller-manuel** [comment]
LGTM, if you add the test we can merge

**Comment by SeanCassiere** [comment]
> LGTM, if you add the test we can merge

Yup, I started with the tests. I guess now I'm a TDD guy 😬

**Comment by SeanCassiere** [comment]
Actually I'll add a test for the util as well before merge.
