### PR TITLE
fix(react-router): restore scroll position onResolved

### LINKED ISSUE #3741: <Link> with hash prop not working as expected since 1.106.0
### Which project does this relate to?

Router

### Describe the bug

I noticed for a while that a Link with hash prop isnt working anymore to scroll to that position in the scroll window. In my own code it works when I click it twice. But in the link below it doesnt work at all since 1.106.0: https://github.com/TanStack/router/compare/v1.105.5...v1.106.0

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-wzvsy46k?file=package.json

### Steps to Reproduce the Bug or Issue

1. Go to page 'Layout B'
2. Click 'middle' on the top
3. Notice it doesnt scroll to the anchor.
4. Now downgrade to 1.105.5
5. repeat step 1 and 2 and notice it works.

### Expected behavior

Using <Link  hash=""> should scroll to the anchor.

### Screenshots or Videos

_No response_

### Platform

- OS: macOS
- Browser:  Chrome
- Version: 135

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by t1nky**
Fixes #3741 

Added hash scroll handling directly in the React `Transitioner` component's `onResolved`, similar to how it's implemented in the Solid version

### CODE REVIEW

**Review by SeanCassiere — COMMENTED** [review]
If I'm not mistaken, this exact same logic is present on `solid-router`.

Perhaps this is logic that can be exported out of `router-core` and then imported (plus setup) in both `react-router` and `solid-router`?

**Comment by t1nky** [comment]
> If I'm not mistaken, this exact same logic is present on `solid-router`.
> 
> Perhaps this is logic that can be exported out of `router-core` and then imported (plus setup) in both `react-router` and `solid-router`?

Good point. I've extracted it into scroll-restoration

**Review by birkskyum — APPROVED** [review]

File: packages/router-core/src/scroll-restoration.ts [hunk 1]
```diff
@@ -316,3 +316,17 @@ export function setupScrollRestoration(router: AnyRouter, force?: boolean) {
     }
   })
 }
+
+export function handleHashScroll(router: AnyRouter) {
```
Comment (SeanCassiere) [inline packages/router-core/src/scroll-restoration.ts:320]: Couple of small changes here please:

- Rename to `handleTransitionerHashScroll`
- Annotate the function with some JSDoc comments marking it as `@internal` with a short description saying that this is to be setup in the `<Transitioner>` component and what it actually does.

**Review by SeanCassiere — CHANGES_REQUESTED** [review]

File: packages/router-core/src/scroll-restoration.ts (hunk 1 above)
Comment (SeanCassiere) [reply packages/router-core/src/scroll-restoration.ts:320]: Optionally, the rename is not necessary if just the JSDoc comment being there.

**Review by SeanCassiere — APPROVED** [review]

**Comment by SeanCassiere** [comment]
@t1nky thank you for contributing this fix!
