### PR TITLE
fix(router): respect `target` attribute on inner component

### LINKED ISSUE #5011: `target` is not respected on link components created with `createLink`
### Which project does this relate to?

Router

### Describe the bug

We have a generic link type in our project which accepts `openInNewTab` as a prop and sets `target` and `rel`:

```tsx
// Details omitted
const MyLink = ({ openInNewTab, href }) => (
	<a
		href={href}
		{...(openInNewTab ? { target: "_blank", rel: "noopener noreferrer" } : {})}
	/>
)

const CreatedMyLink = createLink(MyLink)
```

When we create a link with `openInNewTab` set, it will not open in a new tab and trigger `useBlocker`.

To actually make this work, we have to wrap the created link component again:

```tsx
const Wrapped: LinkComponent<typeof MyLink> = (props) =>
    <CreatedMyLink {...props} target="_blank" />
```

This does work, but since we aren't on react 19 yet, we have to forward the ref. This breaks types and we have to cast the resulting component:

```tsx
const Wrapped: LinkComponent<typeof MyLink> = forwardRef((props, ref) => 
    <CreatedLink ref={ref} {...props} target="_blank" />
) as LinkComponent<typeof MyLink>
```

### Your Example Website or App

https://stackblitz.com/edit/github-bjdswd1c?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

The index page shows all cases I tried and has comments explaining them.

### Expected behavior

I think ideally, setting `target` on the inner component would be respected.

### Screenshots or Videos

_No response_

### Platform

- Router Version: 1.131.22
- OS: Linux
- Browser: Firefox
- Browser Version: 141.0
- Bundler: rsbuild
- Bundler Version: 1.4.11

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leesb971204**
fixes #5011 

## Summary by CodeRabbit

- Bug Fixes
  - Links now correctly respect the target attribute from rendered anchor elements when not explicitly provided as a prop. Clicks on links with target=_blank are no longer intercepted for client-side navigation, opening in a new tab as expected.
  - Explicit target props still override defaults from custom link components, ensuring predictable behavior.
  - Applies to both React Router and Solid Router link components, improving consistency with custom link implementations and browser defaults.

### CODE REVIEW

File: packages/react-router/src/link.tsx [hunk 1]
```diff
@@ -218,11 +218,15 @@ export function useLinkProps<
...
   const handleClick = (e: React.MouseEvent) => {
+    // Check actual element's target attribute as fallback
+    const elementTarget = (e.currentTarget as HTMLAnchorElement).target
+    const effectiveTarget = target !== undefined ? target : elementTarget
+
     if (
       !disabled &&
       !isCtrlEvent(e) &&
       !e.defaultPrevented &&
-      (!target || target === '_self') &&
```
Comment (leesb971204) [inline packages/react-router/src/link.tsx:225]: If the `target` prop is `undefined`, the condition treats it as `_self`, causing the router to intercept the click and prevent `target="_blank"` links from opening in a new tab.

File: packages/react-router/src/link.tsx [hunk 2]
```diff
@@ -218,11 +218,15 @@ export function useLinkProps<
 
   // The click handler
   const handleClick = (e: React.MouseEvent) => {
+    // Check actual element's target attribute as fallback
+    const elementTarget = (e.currentTarget as HTMLAnchorElement).target
+    const effectiveTarget = target !== undefined ? target : elementTarget
+
```
Comment (leesb971204) [inline packages/react-router/src/link.tsx:224]: If no `target` prop is provided, check the rendered element’s `target` attribute to ensure correct behavior.

**Comment by nlynzaad** [comment]
other than making use of test-ids for the tests this looks good to me

**Comment by leesb971204** [comment]
> other than making use of test-ids for the tests this looks good to me

Thank you for the feedback.
I’ve updated it to perform the tests using `data-testid`.

**Comment by nlynzaad** [comment]
one last thing please apply the same tests and update to solid-router

**Comment by leesb971204** [comment]
> one last thing please apply the same tests and update to solid-router

I’ve added the related logic and tests to solid-router.
