### PR TITLE
fix(react-router): incorrectly splitting the key-values pairs from the querystring

### LINKED ISSUE #1404: SearchParams ending in "=" strips the equals sign
### Describe the bug

When using either validateSearch or useSearch() to access the search params, for search params that end in an equals sign, this is being stripped.

For example, below are some examples of what I get

URL: `http://localhost:3000?token=somerandomtoken=`
useSearch(): `{ token=somerandomtoken }`

URL: `http://localhost:3000?token=somerandomtoken=&test=somethingelse`
useSearch(): `{ token: "somerandomtoken", test: "somethingelse" }`

I've checked these same examples against URLSearchParams and this does include the equals sign.

My understanding is that the aim, at least for flat search params, is to behave identical to URLSearchParams to ensure that encoding works with other libraries, therefore this is likely a bug.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-s5pt7g?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the index route
2. Type in the following search param `?token=test=`
3. Check the console and note that the "=" is missing

### Expected behavior

I would expect the returned value in validateSearch and useSearch to be the following:
```ts
{
  token: "test="
}
```

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SeanCassiere**
Updates the ﻿decode function to address parsing issues with querystrings with values containing trailing equal signs.

Previously, query strings like ﻿`token=foo=` were parsed incorrectly as ﻿`{ token: 'foo' }` instead of `﻿{ token: 'foo=' }`.

Closes #1404.

### CODE REVIEW

File: packages/react-router/src/qss.ts [hunk 1]
```diff
@@ -33,18 +52,33 @@ function toValue(mix) {
   return +str * 0 === 0 && +str + '' === str ? +str : str
 }
 
+/**
+ * Decodes a query string into an object.
+ * @param str - The query string to decode.
+ * @param [pfx] - An optional prefix to filter out from the query string.
```
Comment (SeanCassiere) [inline packages/react-router/src/qss.ts:58]: What's the actual intended use-case for the `prefix` variable here?

Is it meant to:

1. Remove a prefix from each key in the string.
Like `prefix = "pre_"`, so `"pre_foo=bar&pre_john=mary"` -> `"{ foo: 'bar', john: 'mary' }"`

2. Or it is just meant to remove some prefix in the string.
Like `prefix = "pre_"`, so its `"pre_foo=bar&john=mary"` -> `"{ foo: 'bar', john: 'mary' }"`

It's not actually used anywhere in the codebase as far as I can tell, if so I can remove the commented tests for it so it only tests for use-cases we've verified it for.

File: packages/react-router/src/qss.ts [hunk 2]
```diff
@@ -33,18 +52,33 @@ function toValue(mix) {
...
+      k = tmp.slice(0, equalIndex)
+      const value = tmp.slice(equalIndex + 1)
+      if (out[k] !== void 0) {
+        out[k] = [].concat(out[k], toValue(value))
+      } else {
+        out[k] = toValue(value)
+      }
     } else {
-      out[k] = toValue(tmp.shift())
+      k = tmp
```
Comment (SeanCassiere) [inline packages/react-router/src/qss.ts:80]: Do we need this?

What happens is that if the key is empty ("?token"), an empty string is assigned to the key in the `out` object,

File: packages/react-router/src/qss.ts (hunk 1 above)
Comment (SeanCassiere) [reply packages/react-router/src/qss.ts:58]: Went through the qss documentation and figured it out. I've added to test to ensure we don't break anything on our end, but we can safely resolve this comment for now.

File: packages/react-router/src/qss.ts (hunk 2 above)
Comment (schiller-manuel) [reply packages/react-router/src/qss.ts:80]: it's not clear-cut
https://stackoverflow.com/a/4557763

I'd leave it in.

Comment (SeanCassiere) [reply packages/react-router/src/qss.ts:80]: I agree.

Also, considering this is for a library meant for the web, it makes sense to emulate what *URLSearchParams* do in the same situation.

image
