### PR TITLE
fix: incorrect route generation for nested layout routes

### LINKED ISSUE #1150: Layout in folder doesn't work
### Describe the bug

Currently this works
/_layout/login.tsx -> /login
auth._layout.login.tsx -> /auth/login

Its just that this doesn't work
/auth/_layout/login.tsx -> /auth/layout/login

As you can see on the reproduction link, the _layout in the /auth/ folder is totally ignored by the router, ignoring my layout.

### Your Example Website or App

https://stackblitz.com/~/edit/github-odjbcq-wjavnw?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

Go on /auth/login, the layout isn't applied.

### Expected behavior

Apply the layout on /auth/_layout pages

### Screenshots or Videos

_No response_

### Platform

- OS: macOS
- Browser: [Edge]
- Version 114.0.1823.82 (Version officielle) (arm64)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SeanCassiere**
I fully acknowledge that this looks jank... there's no escaping this fact.
Most of it stems from having to short-circuit the `handleNode` function.

Fixes #1150

### CODE REVIEW

File: packages/router-generator/src/generator.ts [hunk 1]
```diff
@@ -312,9 +332,40 @@ export async function generator(config: Config) {
       return
     }
 
+    node.isVirtualParentRequired =
+      removeGroups(node.path ?? '')
+        .split('')
+        .filter((char) => char === '/').length >= 2 && // check that the parent route wouldn't be the root route
```
Comment (schiller-manuel) [inline packages/router-generator/src/generator.ts:338]: can the "check that the parent route wouldn't be the root route " be simplified to this?

```tsx
const node.parent?.parent
```

File: packages/router-generator/src/generator.ts [hunk 2]
```diff
@@ -637,6 +690,51 @@ function removeGroups(s: string) {
...
+ * @param {string} variableName - The variable name from which to remove the last segment. Defaults to an empty string.
+ * @returns {string} The variable name with the last segment removed.
+ * @example
+ * removeLastSegmentFromVariableName('RouteBBarTanRoute') // 'RouteBBarTan'
+ * removeLastSegmentFromVariableName('RouteAFoo') // 'RouteA'
+ */
+export function removeLastSegmentFromVariableName(
+  variableName: string = '',
+): string {
+  const segments = variableName.split(/(?=[A-Z])/)
```
Comment (schiller-manuel) [inline packages/router-generator/src/generator.ts:719]: can't we build the variable name again without the last segment instead relying on string manipulations?

File: packages/router-generator/src/generator.ts [hunk 3]
```diff
@@ -312,9 +332,40 @@ export async function generator(config: Config) {
...
+        isVirtualParentRoute: true,
+        isVirtualParentRequired: false,
+      }
+
+      parentNode.children = parentNode.children ?? []
+      parentNode.children.push(node)
+
+      node.parent = parentNode
+
+      await handleNode(parentNode)
```
Comment (schiller-manuel) [inline packages/router-generator/src/generator.ts:361]: can it be a problem that this parentNode is created "on-the-fly"?
e.g. what happens if two routes need the same virtual parent?

File: packages/router-generator/src/generator.ts [hunk 4]
```diff
@@ -216,61 +229,68 @@ export async function generator(config: Config) {
...
     node.isNonLayout = first.endsWith('_')
-    node.cleanedPath = removeGroups(removeUnderscores(node.path) ?? '')
 
-    // Ensure the boilerplate for the route exists
-    const routeCode = fs.readFileSync(node.fullPath, 'utf-8')
-
-    const escapedRoutePath = removeTrailingUnderscores(
-      node.routePath?.replaceAll('$', '$$') ?? '',
+    node.cleanedPath = removeGroups(
+      removeUnderscores(removeLayoutSegments(node.path)) ?? '',
```
[the remark this answers is not in the document]
Comment (SeanCassiere) [reply packages/router-generator/src/generator.ts:238]: Remove layout segments entirely removes blocks that start with `_`, but does not capture those that end with underscores like `/foo_/bar.tsx`.

File: packages/router-generator/src/generator.ts [hunk 5]
```diff
@@ -216,61 +229,68 @@ export async function generator(config: Config) {
...
     )
+    // node.cleanedPath = removeGroups(removeUnderscores(node.path) ?? '')
```
[the remark this answers is not in the document]
Comment (SeanCassiere) [reply packages/router-generator/src/generator.ts:240]: Will do!

File: packages/router-generator/src/generator.ts (hunk 1 above)
Comment (SeanCassiere) [reply packages/router-generator/src/generator.ts:338]: The problem is that this condition never comes to pass.

Since a nested layout route (with no `.route.tsx` configuration file) wouldn't ever be detected as having a parent route because the `routeNodes` array wouldn't already have a virtual parent route to link it to.

In the next chunk of code below is where a virtual parent route is created, the current route is added as its child, and the newly created parent node is mapped to the current node's `.parent` prop.

Comment (SeanCassiere) [reply packages/router-generator/src/generator.ts:344]: There's an alternative that works.

```tsx
const cleanedPathIsEmpty = (node.cleanedPath || '').length === 0
node.isVirtualParentRequired = !cleanedPathIsEmpty && !node.parent && node.isLayout
```
